version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo "Build started on `date`"
      - sudo cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Post build phase completed."

artifacts:
  files:
    - /var/www/html/index.html  # The file to be included as an artifact
